djangopresent/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(),
         name='home'),
    path('registration/', include('registration.urls')),
    path('registration/', include('django.contrib.auth.urls')),
]

registration/urls.py
from django.urls import path

from . import views

app_name = "reg"
urlpatterns = [
    # path("login/", views.LoginView.as_view(),
    #     name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("sigup/", views.SignUpView.as_view(), name="signup")
]

djangopresent/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "index.html"

templates/index.html
{% extends 'layout.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>Home Page</h1>
            <p>Welcome!</p>
            {% if user.is_authenticated %}
            <p>Hi {{ user.username }}!</p>
                <a href="{% url "reg:logout" %}" class="btn btn-primary">Logout</a>
            {% else %}
                <p>You're not Log-in!</p>
                <a href="{% url "reg:signup" %}" class="btn btn-primary">Sign Up</a>
                <a href="{% url "login" %}" class="btn btn-primary">Login</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>